[versions]
kotlin = "2.3.0"
minecraft = "1.21.11"
fabric-loom = "1.15-SNAPSHOT"
fabric-loader = "0.18.4"
fabric-kotlin = "1.13.9+kotlin.2.3.10"
fabric-api = "0.141.3+1.21.11"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-kotlin = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "fabric-kotlin" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
